# Generated by Django 2.0.5 on 2018-08-10 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pedidos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impresion', models.FileField(blank=True, null=True, upload_to=pedidos.models.directorio_pedido)),
            ],
        ),
        migrations.CreateModel(
            name='Archivodos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impresiondos', models.FileField(blank=True, null=True, upload_to=pedidos.models.directorio_pedido)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(blank=True, max_length=250, null=True)),
                ('DIRECCIÓN', models.CharField(blank=True, max_length=200, null=True)),
                ('COLONIA', models.CharField(blank=True, max_length=200, null=True)),
                ('POBLACIÓN', models.CharField(blank=True, max_length=100, null=True)),
                ('MUNICIPIO', models.CharField(blank=True, max_length=150, null=True)),
                ('CP', models.CharField(blank=True, max_length=200, null=True)),
                ('RFC', models.CharField(blank=True, max_length=50, null=True)),
                ('TELÉFONO', models.CharField(blank=True, max_length=50, null=True)),
                ('CORREO', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'permissions': (('vendedor', 'vendedor'), ('cajero', 'cajero'), ('surtidor', 'surtidor'), ('validador', 'validador')),
            },
        ),
        migrations.CreateModel(
            name='DomCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=200, null=True)),
                ('colonia', models.CharField(blank=True, max_length=200, null=True)),
                ('poblacion', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=150, null=True)),
                ('cp', models.CharField(blank=True, max_length=200, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_domicilio', to='pedidos.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerodeorden', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('g', 'generada'), ('a', 'aprobada'), ('c', 'cancelada'), ('v', 'validar'), ('s', 'surtida')], default='a', max_length=1)),
                ('tipoorden', models.CharField(choices=[('CONTADO', 'CONTADO'), ('ANTICIPADO', 'ANTICIPADO'), ('CREDITO', 'CREDITO')], default='CONTADO', max_length=20)),
                ('diasdecredito', models.CharField(choices=[('no', 'no'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default='no', max_length=2)),
                ('otrodomicilio', models.BooleanField(default=False)),
                ('fechageneracion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('referencia_bancaria', models.CharField(blank=True, max_length=50, null=True)),
                ('cargos', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='pedidos.Cliente')),
                ('domicilio_extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_dom', to='pedidos.DomCliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.FloatField(default=0)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.Orden')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='productos.Tarifa')),
            ],
        ),
        migrations.AddField(
            model_name='archivodos',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_dos', to='pedidos.Orden'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='pedidos.Orden'),
        ),
    ]
