"""
Django settings for nfh project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q***v!a9vlqsl8ywsa*(e5=0bqyr=x^(_sv4%g^4!d1!p1gy*u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['142.93.19.134','127.0.0.1','nfhapp.firebaseapp.com','localhost','https://nfhapp.firebaseapp.com/','nacinalferreteradehidalgo.space','https://nacinalferreteradehidalgo.space','www.nacinalferreteradehidalgo.space','https://www.nacinalferreteradehidalgo.space','http://www.nacinalferreteradehidalgo.space','www.nacinalferreteradehidalgo.space','www.nfh.com.mx']


# Application definition

INSTALLED_APPS = [
'admin_view_permission',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'catalogo',
    'pedidos',
    'productos',
    'import_export',
    'searchableselect',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'mathfilters',
    #humanize es la libreria que utiliza django para poder separar los miles en las cantidades
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nfh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nfh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'databasenfh',
        'USER': 'administrator',
        'PASSWORD': 'asdf12345',
        'HOST': 'localhost',
        'PORT': '',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'es-us'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True
#esta variable se pone en false  para poder mostrar el separador de decimales correcto en este caso el'.'
USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT ="/static/"
MEDIA_ROOT = 'exp'
MEDIA_URL = '/exp/'

STATICFILES_DIRS =[
    os.path.join(BASE_DIR, "static")
]
#LOGIN_REDIRECT_URL="player_home"
#LOGOUT_REDIRECT_URL="tictactoe_welcome"
#LOGIN_URL="player_login"



LOGOUT_REDIRECT_URL='accounts:login'


REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
     'DEFAULT_AUTHENTICATION_CLASSES': (
         'rest_framework.authentication.SessionAuthentication',
         'rest_framework.authentication.TokenAuthentication',
         'rest_framework.authentication.BasicAuthentication',


     ),

    'DEFAULT_PERMISSION_CLASSES': [
        #'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
        #'rest_framework.permissions.IsAuthenticated'
        #'rest_framework.permissions.IsAuthenticated',
    ]
}

#corsheaders conf
CORS_ORIGIN_ALLOW_ALL = True

UTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # this is default
    'guardian.backends.ObjectPermissionBackend',
)
DATETIME_INPUT_FORMATS= '%m/%d/%y %H:%M'
